[package]
name = "post-cbindings"
version = "0.1.5"
edition = "2021"


[lib]
name = "post"
crate_type = ["staticlib", "cdylib"]

[dependencies]
eyre = "0.6.8"
post-rs = { path = "../" }

[build-dependencies]
cbindgen = "*"
