[package]
name = "post-cbindings"
version = "0.3.0"
edition = "2021"


[lib]
name = "post"
crate_type = ["staticlib", "cdylib"]

[dependencies]
log = { version = "0.4.17", features = ["std"] }
post-rs = { path = "../" }
scrypt-ocl = { path = "../scrypt-ocl" }

[build-dependencies]
cbindgen = "*"
